# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: 自动化构建 Feat Static Native

on:
  push:
    branches: [ "master" ]
    tags:
      - v**
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Feat Static on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Set up Maven 3.9
        uses: stCarolas/setup-maven@v5
      - name: Update smart-socket version
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            powershell -Command "(Get-Content pom.xml) -replace '<smartsocket.version>1.5.57</smartsocket.version>', '<smartsocket.version>1.6.55</smartsocket.version>' | Set-Content pom.xml"
          else
            sed -i.bak 's/<smartsocket.version>1.5.57<\/smartsocket.version>/<smartsocket.version>1.6.55<\/smartsocket.version>/g' pom.xml
          fi
      - name: Build Feat
        run: mvn -B install --file pom.xml -DskipTests
      - name: Build Feat Static
        run: mvn -B install --file deploy/feat_static/pom.xml -DskipTests

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '23'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build and run HelloWorld.java
        run: |
          native-image -jar deploy/feat_static/target/feat_static-*.jar
#          ./helloworld

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: feat_static-${{ matrix.os }}
          path: feat_static*